// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-students.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_students_default = defineTool({
  name: "list_students",
  title: "List students",
  description: "List students visible to the signed-in user (RLS scoped). Optional filters by batch, program, semester, section, or enrollment_no. Returns up to `limit` rows (default 50, max 200).",
  inputSchema: {
    batch: z.string().optional().describe("Filter by batch (e.g. '2024-CSE')."),
    program: z.string().optional(),
    semester: z.string().optional(),
    section: z.string().optional(),
    enrollment_no: z.string().optional().describe("Exact enrollment number match."),
    search: z.string().optional().describe("Substring match on full_name."),
    limit: z.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("students").select(
      "id, enrollment_no, full_name, email, program, batch, semester, section, year, face_enrolled, enrollment_status"
    ).order("enrollment_no", { ascending: true }).limit(input.limit ?? 50);
    if (input.batch) q = q.eq("batch", input.batch);
    if (input.program) q = q.eq("program", input.program);
    if (input.semester) q = q.eq("semester", input.semester);
    if (input.section) q = q.eq("section", input.section);
    if (input.enrollment_no) q = q.eq("enrollment_no", input.enrollment_no);
    if (input.search) q = q.ilike("full_name", `%${input.search}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { students: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-student-attendance.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_student_attendance_default = defineTool2({
  name: "get_student_attendance",
  title: "Get student attendance summary",
  description: "Return recent attendance records and computed present/absent totals for a single student, looked up by enrollment_no. RLS applies.",
  inputSchema: {
    enrollment_no: z2.string().min(1).describe("Student enrollment number."),
    limit: z2.number().int().min(1).max(500).optional().describe("Max records to return (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ enrollment_no, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data: student, error: sErr } = await supabase.from("students").select("id, enrollment_no, full_name, program, batch, semester, section").eq("enrollment_no", enrollment_no).maybeSingle();
    if (sErr) return { content: [{ type: "text", text: sErr.message }], isError: true };
    if (!student) return { content: [{ type: "text", text: `No student found with enrollment_no ${enrollment_no}` }], isError: true };
    const { data: records, error: rErr } = await supabase.from("attendance_records").select("id, status, confidence, created_at, session_id").eq("student_id", student.id).order("created_at", { ascending: false }).limit(limit ?? 100);
    if (rErr) return { content: [{ type: "text", text: rErr.message }], isError: true };
    const total = records?.length ?? 0;
    const present = records?.filter((r) => r.status === "present").length ?? 0;
    const absent = total - present;
    const percentage = total > 0 ? Math.round(present / total * 1e3) / 10 : null;
    const summary = { student, totals: { total, present, absent, percentage }, records: records ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-attendance-sessions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_attendance_sessions_default = defineTool3({
  name: "list_attendance_sessions",
  title: "List attendance sessions",
  description: "List attendance sessions visible to the signed-in user (RLS scoped). Optional filters by batch, subject, and date range.",
  inputSchema: {
    batch: z3.string().optional(),
    subject: z3.string().optional(),
    from_date: z3.string().optional().describe("ISO date lower bound, inclusive."),
    to_date: z3.string().optional().describe("ISO date upper bound, inclusive."),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let q = supabase.from("attendance_sessions").select("id, date, subject, batch, faculty_name, method, total_present, total_absent, created_at").order("date", { ascending: false }).limit(input.limit ?? 50);
    if (input.batch) q = q.eq("batch", input.batch);
    if (input.subject) q = q.eq("subject", input.subject);
    if (input.from_date) q = q.gte("date", input.from_date);
    if (input.to_date) q = q.lte("date", input.to_date);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { sessions: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-lecture-targets.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_lecture_targets_default = defineTool4({
  name: "list_lecture_targets",
  title: "List lecture targets",
  description: "List lecture / attendance targets visible to the signed-in user (RLS scoped). Optional filters by batch and subject.",
  inputSchema: {
    batch: z4.string().optional(),
    subject: z4.string().optional(),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    let q = supabase.from("lecture_targets").select("*").limit(input.limit ?? 50);
    if (input.batch) q = q.eq("batch", input.batch);
    if (input.subject) q = q.eq("subject", input.subject);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { targets: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bzfnyhlvmesonfxapncc";
var mcp_default = defineMcp({
  name: "eduvista-mcp",
  title: "EduVista MCP",
  version: "0.1.0",
  instructions: "Tools for the EduVista attendance platform. Use `list_students` to browse the roster, `get_student_attendance` to inspect one student's history and percentage, `list_attendance_sessions` for recent classroom sessions, and `list_lecture_targets` for configured attendance targets. All calls act as the signed-in user (admin or faculty) and respect the app's row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_students_default, get_student_attendance_default, list_attendance_sessions_default, list_lecture_targets_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
